version: '3.4'

services:

  traderplatform.engine:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # ports:
    #   - "${PORT_ENGINE}:${PORT_ENGINE}"
    #   - "${PORT_ENGINE_SSL}:${PORT_ENGINE_SSL}"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  traderplatform.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  traderplatform.daemon:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
