version: '3.4'

services:

  traderplatform.database:
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=my-secret-pw

  traderplatform.engine:
    build:
      args:
        - MODE=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "${PORT_ENGINE}:80"

  traderplatform.api:
    build:
      args:
        - MODE=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
    ports:
      - "${PORT_API}:80"

  traderplatform.daemon:
    build:
      args:
        - MODE=Debug
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
