version: '3.4'

services:

  traderplatform.database:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    ports:
      - "27017:27017"

  traderplatform.engine:
    build:
      args:
        - MODE=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "${PORT_ENGINE}:80"

  traderplatform.api:
    build:
      args:
        - MODE=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    ports:
      - "${PORT_API}:80"

  traderplatform.daemon:
    build:
      args:
        - MODE=Debug
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
