version: '3.4'

services:

  traderplatform.engine:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "${PORT_ENGINE}:80"

  traderplatform.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "${PORT_API}:80"

  traderplatform.daemon:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
