version: '3.4'

services:

  traderplatform.mongodb:
    container_name: TraderPlatform.MongoDB
    image: traderplatform-mongodb
    build:
      context: .
      dockerfile: mongo/mongo.Dockerfile
    volumes:
      - ./.volumes/mongo/db:/data/db
      - ./.volumes/mongo/configdb:/data/configdb

  # traderplatform.nginx:
  #   container_name: TraderPlatform.nginx
  #   image: traderplatform-nginx
  #   build:
  #     context: .
  #     dockerfile: nginx/nginx.Dockerfile
  #   depends_on:
  #     # - traderplatform.certbot
  #     - traderplatform.api
  #   environment:
  #     - DOMAIN
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./.volumes/certbot/www:/var/www/certbot/:ro
  #     - ./.volumes/certbot/etc/letsencrypt:/etc/letsencrypt:ro
  #     - ./.volumes/certbot/var/lib/letsencrypt:/var/lib/letsencrypt:ro
  #   command: "/bin/sh -c 'while :; do sleep 4h & wait $${!}; nginx -s reload; done;'"

  # traderplatform.certbot:
  #   container_name: TraderPlatform.Certbot
  #   image: certbot/certbot:latest
  #   depends_on:
  #     - traderplatform.nginx
  #   volumes:
  #     - ./.volumes/certbot/www:/var/www/certbot/:rw
  #     - ./.volumes/certbot/etc/letsencrypt:/etc/letsencrypt:rw
  #     - ./.volumes/certbot/var/lib/letsencrypt:/var/lib/letsencrypt:rw
  #   command: certonly --webroot -w /var/www/certbot --email ${EMAIL} --no-eff-email -d ${DOMAIN} --agree-tos
  #   entrypoint: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; certbot renew; done;'"

  traderplatform.engine:
    container_name: TraderPlatform.Engine
    image: ${DOCKER_REGISTRY-}traderplatform-engine
    build:
      context: .
      dockerfile: TraderPlatform.Engine/Dockerfile

  traderplatform.api:
    container_name: TraderPlatform.API
    image: ${DOCKER_REGISTRY-}traderplatform-api
    build:
      context: .
      dockerfile: TraderPlatform.API/Dockerfile
    depends_on:
      - traderplatform.mongodb
      - traderplatform.engine
    environment:
      - ADDRESS_ENGINE=http://traderplatform.engine

  traderplatform.daemon:
    container_name: TraderPlatform.Daemon
    image: ${DOCKER_REGISTRY-}traderplatform-daemon
    build:
      context: .
      dockerfile: TraderPlatform.Daemon/Dockerfile
    depends_on:
      - traderplatform.mongodb
      - traderplatform.api
    environment:
      - ADDRESS_API=http://traderplatform.api

networks:
  default:
    name: traderplatformcore
    driver: bridge