version: '3.4'

services:

  traderplatform.database:
    image: mariadb:latest

  # traderplatform.redis:
  #   image: redis:alpine

  traderplatform.nginx:
    image: nginx:alpine

  traderplatform.engine:
    image: ${DOCKER_REGISTRY-}traderplatform-engine
    build:
      context: .
      dockerfile: TraderPlatform.Engine/Dockerfile

  traderplatform.api:
    image: ${DOCKER_REGISTRY-}traderplatform-api
    build:
      context: .
      dockerfile: TraderPlatform.API/Dockerfile

  traderplatform.daemon:
    image: ${DOCKER_REGISTRY-}traderplatform-daemon
    build:
      context: .
      dockerfile: TraderPlatform.Daemon/Dockerfile
