version: '3.4'

networks:
  TraderPlatform:
    driver: bridge

services:

  traderplatform.database:
    container_name: traderplatform.database
    image: mariadb:latest
    networks:
      - TraderPlatform

  # traderplatform.redis:
  #   container_name: traderplatform.redis
  #   image: redis:alpine
  #   networks:
  #     - TraderPlatform

  # traderplatform.nginx:
  #   container_name: traderplatform.nginx
  #   image: nginx:alpine
  #   networks:
  #     - TraderPlatform

  traderplatform.engine:
    image: ${DOCKER_REGISTRY-}traderplatform-engine
    build:
      context: .
      dockerfile: TraderPlatform.Engine/Dockerfile
    networks:
      - TraderPlatform

  traderplatform.api:
    image: ${DOCKER_REGISTRY-}traderplatform-api
    build:
      context: .
      dockerfile: TraderPlatform.API/Dockerfile
    depends_on:
      - traderplatform.database
      - traderplatform.engine
    environment:
      - ADDRESS_ENGINE=http://traderplatform.engine
    networks:
      - TraderPlatform

  traderplatform.daemon:
    image: ${DOCKER_REGISTRY-}traderplatform-daemon
    build:
      context: .
      dockerfile: TraderPlatform.Daemon/Dockerfile
    depends_on:
      - traderplatform.api
    environment:
      - ADDRESS_API=http://traderplatform.api
    networks:
      - TraderPlatform
